### ISSUE TITLE
Suggestion: Inventory tracking

### ISSUE THREAD

**Issue by joaomoraes** [WotVFarmCalculator/wotvfarmcalculator.github.io#1]
Great tool! Would like to suggest incorporating some kind of inventory and then taking it into consideration when showing the places to farm. Are you interested on PRs?

**Comment by WotVFarmCalculator** [comment]
Yep, I would love PRs.

**Comment by WotVFarmCalculator** [comment]
I'm going to track this as #23 going forward.
