### ISSUE TITLE
Typo: 'Team' names (Fortem, Nitor) getting stripped from mission names

### ISSUE THREAD

**Issue by jqassar** [WotVFarmCalculator/wotvfarmcalculator.github.io#12]
When one of the mission results has the name of a 'team' in it with double angle brackets (e.g. the <...<...Fortem...>...> missions, the inner set of angle brackets along with the team name is stripped so you see '<>...' instead.  Very minor issue, but might confuse some.

**Comment by WotVFarmCalculator** [comment]
Thanks! This is fixed now. I changed it to use the opening/closing guillemets instead.  ex: `«Fortem»` Which is what the game itself uses, I believe.
