### ISSUE TITLE
Axe Azurite incorrectly showing for 1:3:7 "What has been Lost"

### ISSUE THREAD

**Issue by Kibblezzz** [WotVFarmCalculator/wotvfarmcalculator.github.io#27]
Does not contain Axe azurite.

Thank you very much for creating this calculator! I use it all the time

**Comment by WotVFarmCalculator** [comment]
Thanks! I'll take a look and get it fixed ASAP.

**Comment by WotVFarmCalculator** [comment]
This is now resolved. It looks like I meant to put it on 1:3:8 but put it on 1:3:7 by accident. I've removed it from 1:3:7 and added it to 1:3:8.
