### ISSUE TITLE
Add column for # of enemies

### ISSUE THREAD

**Issue by WotVFarmCalculator** [WotVFarmCalculator/wotvfarmcalculator.github.io#5]
This is currently blocked b/c we lack the raw data.

**Comment by TheBlueSmoke** [comment]
Hey, did you start working on this? I wouldn't mind giving it an attempt, although it might be slow.

**Comment by WotVFarmCalculator** [comment]
@TheBlueSmoke I haven't started any dev because of the lack of data. But if you have the data then go for it! Thanks!

**Comment by WotVFarmCalculator** [comment]
This has been completed as part of the beta branch work.
