### ISSUE TITLE
Missing item: "Joyful Heart"

### ISSUE THREAD

**Issue by SteveRussell33** [WotVFarmCalculator/wotvfarmcalculator.github.io#59]
Equipment item "Joyful Heart" is missing

**Comment by WotVFarmCalculator** [comment]
@SteveRussell33 I'm not seeing this item in any of the drop tables. Do you know which quest drops it?

**Comment by WotVFarmCalculator** [comment]
The internal name for Joyful Heart is `IT_AF_MAT_HEART_04`, for my future reference.

**Comment by SteveRussell33** [comment]
I think it might be from Chocobo Expeditions only. I've only gotten 1 of them in just over a month playing Global. Seems UR-ish.

**Comment by WotVFarmCalculator** [comment]
Ah, that's the problem. Currently, my tool only looks at items that are dropped from quests.
