### ISSUE TITLE
FINAL FANTASY TACTICS Battle #2 [Intermediate] has 6 enemies

### ISSUE THREAD

**Issue by Kernith** [WotVFarmCalculator/wotvfarmcalculator.github.io#60]
FINAL FANTASY TACTICS Battle #2 [Intermediate] has 6 enemies, not 5.  Missing a red chocobo (for 2 total).  Pretty minor, but maybe evidence something is amiss

**Comment by WotVFarmCalculator** [comment]
Thanks for the report, I'll look into it!
