### ISSUE TITLE
Feature Request: 'One shot-able' indicator/flag

### ISSUE THREAD

**Issue by Icydeath** [WotVFarmCalculator/wotvfarmcalculator.github.io#62]
An indicator that the quest can be cleared with 1 AoE and with what character.

This would be helpful when trying to identify the fastest clearing with the best drops rate for a specific item.

**Comment by WotVFarmCalculator** [comment]
Heya, thanks for the suggestion but this was suggested awhile back and I decided not to implement it. See https://github.com/WotVFarmCalculator/wotvfarmcalculator.github.io/issues/18

The list of quests where this would apply is so short that I don't feel it would be useful to squeeze into the (already cramped) UI. 

I'm hoping that https://github.com/WotVFarmCalculator/wotvfarmcalculator.github.io/issues/17 will resolve the issue for individual users in the future.
