### ISSUE TITLE
Incorrect Elemental Material Given for Vadim

### ISSUE THREAD

**Issue by acedamace** [WotVFarmCalculator/wotvfarmcalculator.github.io#65]
Not sure if this is the right place to put this but it's just a small problem.  When querying for the material for Vadim, it gives earth elemental material instead of lightning elemental material of which he is.  Photos attached.  Thanks for everything though, this has been a great help!

![image](https://user-images.githubusercontent.com/54158102/83339938-4683e880-a298-11ea-9f75-b7342304a168.png)
![image](https://user-images.githubusercontent.com/54158102/83339940-4c79c980-a298-11ea-8bd4-e89887ff8bd6.png)

**Comment by WotVFarmCalculator** [comment]
Thanks for the report. This ideally will be fixed with #40 .

**Comment by WotVFarmCalculator** [comment]
This has been fixed.
