### ISSUE TITLE
Yellow Memories still recorded as double drops?

### ISSUE THREAD

**Issue by slgray16** [WotVFarmCalculator/wotvfarmcalculator.github.io#68]
Yellow Memories
1:5:1:7 First Things First 
42.1% for 6 energy 
The farming tool says (2x) but I feel like that is a bug leftover from double drops.    

I refreshed and I am on your latest build with this update:

_June 18th: Added the ability to show expired and upcoming quests (if they are available)._

**Comment by WotVFarmCalculator** [comment]
Thanks for the report. The tool doesn't currently reflect any sort of double drop campaigns that are going on. The way gumi structures the campaign/event/multiplayer data makes it somewhat convoluted to get an accurate value for that. 

In any case, the 2x is indeed the non-doubled correct value for that quest (in the data). Are you seeing a different value in the game?

**Comment by slgray16** [comment]
You are correct.   I ran a few tests to confirm.  Luckily on one run the first enemy I killed dropped x2 yellow memories.   The chest indicated a single "drop" but upon examination it really was 2 yellow memories.

It's certainly confusing.  My apologies for the false report.

**Comment by WotVFarmCalculator** [comment]
No worries.
