### ISSUE TITLE
Faded Icons of Material included as part of the Quest wasn't filtered in

### ISSUE THREAD

**Issue by Akerszp** [WotVFarmCalculator/wotvfarmcalculator.github.io#71]
It's nice that you can see what quest you can check for but it would also be nice to have on the right side (as a faded icon) all other materials you can potentially get from the quest in case you might have missed something to filter in.

Or if you have too much of another material you can see which quest to not do based on the extra materials you may potentially get.

**Comment by WotVFarmCalculator** [comment]
@JSharpie If I'm understanding you correctly, it sounds like you might not know about the ability to expand to show the full drop table. If you click the little arrow on the left side you'll see what I mean.

![image](https://user-images.githubusercontent.com/63118703/87989501-20b4dc00-cab0-11ea-97ee-98bb0d735a60.png)
